# Generated by Django 4.1.3 on 2022-12-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('jefe_directo', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('id_persona', models.IntegerField()),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=100)),
                ('id_boleta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('unidad_venta', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('posicion', models.CharField(max_length=100)),
                ('codigo_producto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('codigo_producto', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=100)),
                ('iva', models.IntegerField()),
                ('precio_total', models.IntegerField()),
                ('numero_boleta', models.IntegerField()),
                ('id_producto', models.IntegerField()),
            ],
        ),
    ]
